package vsb.cec0094.bachelorProject.models;

public enum Action {
    PICK_CARD, FACE_CARD, GET_CARD, SHOW_FACED_EXPEDITION_ON_EXPEDITIONS_PACK, SHOW_FACED_EXPEDITION_ON_TABLE,
    SHOW_EXPEDITION_WHICH_WILL_BE_TAKEN
}
