package vsb.cec0094.bachelorProject.gameLogic.card;

public enum CardType {
    PINACE, FLUTE, SKIFF, FRIGATE, GALLEON, //ships
    TRADER, SETTLER, CAPTAIN, PRIEST, JACK_OF_ALL_TRADES, SAILOR, PIRATE, MADEMOISELLE, JESTER, ADMIRAL, GOVERNOR,
    TRADER_PINACE, TRADER_FLUTE, TRADER_SKIFF, TRADER_FRIGADE, TRADER_GALLEON, //characters
    EXPEDITION,
    TAX_INFLUENCE, TAX_SWORDS
}
