package vsb.cec0094.bachelorProject.gameLogic.card;

public enum CardType {
    PINACE, FLUTE, BRIGA, FRIGATE, GALLEON, //ships
    TRADER, SETTLER, CAPTAIN, PRIEST, JACK_OF_ALL_TRADES, SAILOR, PIRATE, MADEMOISELLE, JESTER, ADMIRAL, GOVERNOR, //characters
    EXPEDITION,
    TAX_INFLUENCE, TAX_SWORDS
}
