INSERT INTO gameinqueue (id, maxPlayersCount, owner) VALUES(0, 3, 'adam');
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', 0);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam2', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam3', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam4', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam5', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam6', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam7', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam8', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam9', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO players (login, enabled, password, game_id) VALUES ('adam10', '1', '$2a$12$CjUXhURzGFkPwuAMTNxtVOYXlJg9faP7aEmhV8FkTAFVosHcJP.Dy', null);
INSERT INTO User_roles (id, user_role, login) VALUES (0, 'ROLE_USER', 'adam');
INSERT INTO User_roles (id, user_role, login) VALUES (2, 'ROLE_USER', 'adam2');
INSERT INTO User_roles (id, user_role, login) VALUES (3, 'ROLE_USER', 'adam3');
INSERT INTO User_roles (id, user_role, login) VALUES (4, 'ROLE_USER', 'adam4');
INSERT INTO User_roles (id, user_role, login) VALUES (5, 'ROLE_USER', 'adam5');
INSERT INTO User_roles (id, user_role, login) VALUES (6, 'ROLE_USER', 'adam6');
INSERT INTO User_roles (id, user_role, login) VALUES (7, 'ROLE_USER', 'adam7');
INSERT INTO User_roles (id, user_role, login) VALUES (8, 'ROLE_USER', 'adam8');
INSERT INTO User_roles (id, user_role, login) VALUES (9, 'ROLE_USER', 'adam9');
INSERT INTO User_roles (id, user_role, login) VALUES (10, 'ROLE_USER', 'adam10');
INSERT INTO User_roles (id, user_role, login) VALUES (11, 'ROLE_ADMINISTRATOR', 'adam');
